library(readxl)
library(tidyverse)
library(rpart)
library(rpart.plot)
library(lmtest)
library(sandwich)
library(stargazer)
library(coefplot)
CleanEnergy <- read_excel("C:/Users/alexa/Downloads/CleanEnergy.xlsx",
sheet = "Sheet3")
CleanEnergy$Energyprice <- as.numeric(CleanEnergy$Energyprice)
CleanEnergy$Country <- as.factor(CleanEnergy$Country)
treepooled <- rpart(Energyprice~Year+factor(Country),data=CleanEnergy)
summary(treepooled)
pdf("tree_plot.pdf", width = 20, height = 15)
rpart.plot(treepooled, type = 1, extra = 101, tweak = 1.5, cex = 0.7)
dev.off()
control <- c("Sweden","Denmark","France","Slovenia")
dependent <- c("Germany","Italy","Czechia","Netherlands","Greece")
panel_df <- CleanEnergy %>%
mutate(
control = ifelse(Country %in% control, 1, 0),
treatment= ifelse(Country %in% dependent,1,0),
corrosion = ifelse(Country=="France"&Year%in%c(6,7),1,0))
treatment_control_df <- panel_df %>%
filter(treatment + control == 1)
pd <- position_dodge(0.2)
ggplot(treatment_control_df,aes(x=Year,y=Energyprice,colour = factor(treatment)))+stat_summary(fun=mean,geom="line",position = pd) + stat_summary(fun.data = mean_cl_boot,geom="errorbar",position = pd)+stat_summary(fun=mean,geom="point",position = pd)+geom_vline(xintercept = 6,linetype="dashed")+theme_bw()
ggplot(treatment_control_df,aes(x=Year,y=Energyprice,colour = factor(treatment)))+geom_point()+geom_smooth(method = "loess",se=FALSE)+theme_bw()
ggplot(treatment_control_df,aes(x=Year,y=Energyprice,colour = factor(interaction(treatment,Crisis,corrosion))))+geom_point()+geom_smooth(method="loess",se=FALSE)+theme_bw()
ggplot(treatment_control_df,aes(x=Year,y=Energyprice,colour = factor(interaction(treatment,Crisis))))+geom_point()+geom_smooth(method="lm",se=FALSE)+theme_bw()
pooledols <- lm(Energyprice~factor(Crisis)+factor(treatment)+factor(Crisis)*factor(treatment)+factor(corrosion),data=treatment_control_df)
olsyearfe <- lm(Energyprice~factor(Year)+factor(Crisis)+factor(treatment)+factor(Crisis)*factor(treatment),data=treatment_control_df)
olscfe <- lm(Energyprice~Country+factor(Crisis)+factor(treatment)+factor(Crisis)*factor(treatment)+factor(corrosion),data=treatment_control_df)
olsyearcfe <- lm(Energyprice~factor(Year)+factor(Crisis)+factor(treatment)+factor(Crisis)*factor(treatment)+Country+factor(corrosion),data=treatment_control_df)
AIC(pooledols,olsyearfe,olscfe,olsyearcfe)
BIC(pooledols,olsyearfe,olscfe,olsyearcfe)
anova(olscfe)
bptest(olscfe)
coeftest(olscfe,vcov. = vcovHC(olscfe,type="HC1"))
stargazer(pooledols,olscfe,olsyearcfe,type = "text")
coefplot(olscfe)